### ISSUE TITLE
Fix the Donate Page on Mobile

### ISSUE THREAD

**Issue by ElsieNoel** [alansouzati/zozu-sponsor-portal#5]
![IMG_2821.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5e3c9266e8980013cd51cc/125516c66e82c728ace21e0d46c1b9bd1cd0dbfbdeabf301b44fff9e2c4533317346f62a2581b571ee402f505b0c1df941585947f5af8a28afb02e6c981e5ab38532022d8c6853beb2901eb80bbb258a4984b2bd8345c8eb3f24f5c6.jpeg)

**Comment by ElsieNoel** [comment]
The mobile appearance of the donate page is a little buggy.

**Comment by alansouzati** [comment]
This is now fixed

![fix_button.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555234953a6a9e8f00e8ff55/125516c66e82c728ace21e0d46ee9d821c8096bd9be6b101e81fe086264c22703d46f9692584b62ce91b2a035b5e4aff120d5f44fafa807da5b53576984019af80330b2b9b645bf9fa9015ad03ba2a8a4a84b0bf884dc3ed3c26e3899d02.gif)
