### ISSUE TITLE
Mobile Check

### ISSUE THREAD

**Issue by ElsieNoel** [alansouzati/zozu-sponsor-portal#8]
Any elements that don't look good on mobile need changing. Pulling up every page on mobile and double-checking that it looks good.

**Comment by alansouzati** [comment]
Site looks good on mobile now

![Screen Shot 2018-01-20 at 12.25.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555234953a6a9e8f00e8ff55/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f36b7191a379ed0c2954415e4fbc21254d58eeb9cb74fce36f34985619e880680b72cf3c43a8b9864cec54ba208d4c8ce0bf8945c6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae7495da4133760e3773f6e0a.png)

Also simplified the vimeo annotations to remove the text overlay on top of the video :+1
